import { Router } from "express";
import rateLimit from "express-rate-limit";
import bcrypt from "bcryptjs";
import { randomUUID, createHash } from "node:crypto";
import { and, desc, eq, gt, inArray, isNull, ne, or, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "../config/db.js";
import { announcementAreas, announcementReads, announcements, areas, authSessions, employeeAreas, employees, payslipVersions, payslips, permissions, rolePermissions, roles, userRoles, users } from "../db/schema.js";
import { authenticateJWT, requirePermission } from "../middlewares/auth.js";
import { validate } from "../middlewares/validate.js";
import { asyncHandler, ApiError } from "../utils/api-error.js";
import { audit } from "../utils/audit.js";
import { newSessionId, refreshExpiry, signAccessToken, signRefreshToken, verifyRefreshToken } from "../utils/tokens.js";
import { getIdentity } from "../services/identity.service.js";
import { changeOwnPassword, resetPasswordWithTemporaryCredential, updateUserAccountState } from "../services/user-security.service.js";
import { buildPayslipPath, createPayslipDownloadUrl, createPayslipUploadUrl, createPayslipViewUrl, verifyPayslipObject } from "../services/storage.service.js";

const router = Router();
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false, message: { error: "Demasiados intentos. Intente más tarde." } });
const UUID = z.string().uuid();
const monthNames = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];
// `z.coerce.date()` convierte `null` en 1970-01-01. Para avisos, null y un
// campo vacío significan explícitamente que no hay vencimiento.
const createAnnouncementExpiry = z.preprocess((value) => value == null || value === "" ? null : value, z.coerce.date().nullable());
const updateAnnouncementExpiry = z.preprocess((value) => value === null || value === "" ? null : value, z.coerce.date().nullable().optional());
const hashToken = (token) => createHash("sha256").update(token).digest("hex");
const cookieOptions = () => ({ httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", maxAge: Number(process.env.JWT_REFRESH_TTL_SECONDS || 1209600) * 1000, path: "/api/auth" });
const userDto = (identity) => ({ id: identity.id, email: identity.email, username: identity.username, employeeId: identity.employeeId, permissions: identity.permissions, roles: identity.roles, mustChangePassword: identity.mustChangePassword });
async function issueSession(req, res, user) {
  const id = newSessionId(); const refresh = signRefreshToken(user.id, id);
  await db.insert(authSessions).values({ id, userId: user.id, refreshTokenHash: hashToken(refresh), expiresAt: refreshExpiry(), ipAddress: req.ip, userAgent: req.get("user-agent") });
  res.cookie("refresh_token", refresh, cookieOptions());
  return signAccessToken(user.id);
}
function requirePasswordChange(req, res, next) {
  if (req.user.mustChangePassword) {
    return next(new ApiError(403, "Debe cambiar su contraseña antes de continuar"));
  }
  return next();
}

router.post("/auth/login", loginLimiter, validate(z.object({ body: z.object({ identifier: z.string().min(1), password: z.string().min(1) }) })), asyncHandler(async (req, res) => {
  const { identifier, password } = req.validated.body;
  const [user] = await db.select().from(users).where(or(sql`lower(${users.email}) = lower(${identifier})`, sql`lower(${users.username}) = lower(${identifier})`));
  if (!user || !user.active || !(await bcrypt.compare(password, user.passwordHash))) throw new ApiError(401, "Usuario o contraseña incorrectos");
  await db.update(users).set({ lastLoginAt: new Date(), updatedAt: new Date() }).where(eq(users.id, user.id));
  const identity = await getIdentity(user.id); const accessToken = await issueSession(req, res, user);
  req.user = identity; await audit(req, "AUTH_LOGIN", "user", user.id);
  res.json({ accessToken, user: userDto(identity) });
}));
router.post("/auth/refresh", asyncHandler(async (req, res) => {
  const token = req.cookies.refresh_token; if (!token) throw new ApiError(401, "Sesión no disponible");
  let payload; try { payload = verifyRefreshToken(token); } catch { throw new ApiError(401, "Sesión vencida"); }
  const [session] = await db.select().from(authSessions).where(and(eq(authSessions.id, payload.sid), eq(authSessions.refreshTokenHash, hashToken(token)), isNull(authSessions.revokedAt), gt(authSessions.expiresAt, new Date())));
  if (!session) throw new ApiError(401, "Sesión revocada");
  await db.update(authSessions).set({ revokedAt: new Date() }).where(eq(authSessions.id, session.id));
  const identity = await getIdentity(payload.sub); if (!identity) throw new ApiError(401, "Usuario inactivo");
  const accessToken = await issueSession(req, res, identity); res.json({ accessToken, user: userDto(identity) });
}));
router.post("/auth/logout", asyncHandler(async (req, res) => { const token = req.cookies.refresh_token; if (token) await db.update(authSessions).set({ revokedAt: new Date() }).where(eq(authSessions.refreshTokenHash, hashToken(token))); res.clearCookie("refresh_token", cookieOptions()); await audit(req, "AUTH_LOGOUT", "session"); res.status(204).end(); }));
router.get("/auth/me", authenticateJWT, (req, res) => res.json({ user: userDto(req.user) }));
router.post("/auth/change-password", authenticateJWT, validate(z.object({ body: z.object({ currentPassword: z.string().min(1), newPassword: z.string().min(12) }) })), asyncHandler(async (req, res) => { const { currentPassword, newPassword } = req.validated.body; await changeOwnPassword(req.user.id, currentPassword, newPassword); await audit(req, "PASSWORD_CHANGED", "user", req.user.id); res.status(204).end(); }));

// El perfil y el cambio de contraseña quedan disponibles antes de este punto.
// El resto de la API exige resolver la credencial temporal obligatoria.
router.use(authenticateJWT, requirePasswordChange);
// Los gestores de avisos sólo necesitan leer las áreas activas para elegir una audiencia;
// la administración de áreas sigue requiriendo EMPLOYEE_MANAGE en los endpoints mutables.
router.get("/areas", (req,res,next) => req.user.permissions.includes("EMPLOYEE_MANAGE") || req.user.permissions.includes("ANNOUNCEMENT_MANAGE") ? next() : next(new ApiError(403,"No tiene permisos para esta acción")), asyncHandler(async (req,res) => res.json({ items: await db.select().from(areas).orderBy(areas.name) })));
router.post("/areas", requirePermission("EMPLOYEE_MANAGE"), validate(z.object({ body: z.object({ code:z.string().min(1).max(30), name:z.string().min(1).max(120), description:z.string().max(500).optional() }) })), asyncHandler(async (req,res) => { const item={ id:randomUUID(), ...req.validated.body }; await db.insert(areas).values(item); await audit(req,"AREA_CREATED","area",item.id); res.status(201).json({ item }); }));
router.patch("/areas/:id", requirePermission("EMPLOYEE_MANAGE"), validate(z.object({ params:z.object({id:UUID}), body:z.object({ code:z.string().min(1).max(30).optional(), name:z.string().min(1).max(120).optional(), description:z.string().max(500).nullable().optional(), active:z.boolean().optional() }) })), asyncHandler(async (req,res) => { await db.update(areas).set({ ...req.validated.body, updatedAt:new Date() }).where(eq(areas.id,req.validated.params.id)); await audit(req,"AREA_UPDATED","area",req.validated.params.id); res.status(204).end(); }));
router.get("/employees", requirePermission("EMPLOYEE_MANAGE"), asyncHandler(async (req,res) => { const q=(req.query.q||"").toString(); const items=await db.select().from(employees).where(q ? sql`lower(${employees.firstName} || ' ' || ${employees.lastName} || ' ' || ${employees.employeeNumber}) like lower(${'%'+q+'%'})` : undefined).orderBy(employees.lastName); const joins=await db.select().from(employeeAreas); res.json({items:items.map(item=>({...item,areaIds:joins.filter(j=>j.employeeId===item.id).map(j=>j.areaId)}))}); }));
router.post("/employees", requirePermission("EMPLOYEE_MANAGE"), validate(z.object({body:z.object({employeeNumber:z.string().min(1),firstName:z.string().min(1),lastName:z.string().min(1),areaIds:z.array(UUID).default([])})})), asyncHandler(async(req,res)=>{const item={id:randomUUID(),...req.validated.body}; await db.insert(employees).values(item); if(item.areaIds.length) await db.insert(employeeAreas).values(item.areaIds.map(areaId=>({employeeId:item.id,areaId}))); await audit(req,"EMPLOYEE_CREATED","employee",item.id);res.status(201).json({item});}));
router.patch("/employees/:id",requirePermission("EMPLOYEE_MANAGE"),validate(z.object({params:z.object({id:UUID}),body:z.object({employeeNumber:z.string().min(1).optional(),firstName:z.string().min(1).optional(),lastName:z.string().min(1).optional(),active:z.boolean().optional(),areaIds:z.array(UUID).optional()})})),asyncHandler(async(req,res)=>{const {areaIds,...data}=req.validated.body; await db.update(employees).set({...data,updatedAt:new Date()}).where(eq(employees.id,req.validated.params.id));if(areaIds){await db.delete(employeeAreas).where(eq(employeeAreas.employeeId,req.validated.params.id));if(areaIds.length)await db.insert(employeeAreas).values(areaIds.map(areaId=>({employeeId:req.validated.params.id,areaId})));}await audit(req,"EMPLOYEE_UPDATED","employee",req.validated.params.id);res.status(204).end();}));

router.get("/users",requirePermission("USER_MANAGE"),asyncHandler(async(req,res)=>{const items=await db.select({id:users.id,email:users.email,username:users.username,active:users.active,mustChangePassword:users.mustChangePassword,employeeId:employees.id,employeeNumber:employees.employeeNumber,firstName:employees.firstName,lastName:employees.lastName}).from(users).leftJoin(employees,eq(employees.userId,users.id));const assignments=await db.select({userId:userRoles.userId,role:roles.name}).from(userRoles).innerJoin(roles,eq(userRoles.roleId,roles.id));res.json({items:items.map(i=>({...i,roles:assignments.filter(a=>a.userId===i.id).map(a=>a.role)}))});}));
router.post("/users",requirePermission("USER_MANAGE"),validate(z.object({body:z.object({email:z.string().email(),username:z.string().min(3).max(60).optional(),password:z.string().min(12),employeeId:UUID.optional(),roleIds:z.array(UUID).min(1)})})),asyncHandler(async(req,res)=>{const {password,employeeId,roleIds,...data}=req.validated.body;const id=randomUUID();await db.insert(users).values({id,...data,passwordHash:await bcrypt.hash(password,12),mustChangePassword:true});if(employeeId)await db.update(employees).set({userId:id,updatedAt:new Date()}).where(eq(employees.id,employeeId));await db.insert(userRoles).values(roleIds.map(roleId=>({userId:id,roleId})));await audit(req,"USER_CREATED","user",id);res.status(201).json({id});}));
router.patch("/users/:id",requirePermission("USER_MANAGE"),validate(z.object({params:z.object({id:UUID}),body:z.object({active:z.boolean().optional(),employeeId:UUID.nullable().optional(),roleIds:z.array(UUID).optional(),forcePasswordChange:z.boolean().optional()})})),asyncHandler(async(req,res)=>{const {employeeId,roleIds,active,forcePasswordChange}=req.validated.body;await updateUserAccountState(req.validated.params.id,{active,forcePasswordChange});if(employeeId!==undefined){await db.update(employees).set({userId:null}).where(eq(employees.userId,req.validated.params.id));if(employeeId)await db.update(employees).set({userId:req.validated.params.id}).where(eq(employees.id,employeeId));}if(roleIds){await db.delete(userRoles).where(eq(userRoles.userId,req.validated.params.id));if(roleIds.length)await db.insert(userRoles).values(roleIds.map(roleId=>({userId:req.validated.params.id,roleId})));}await audit(req,"USER_UPDATED","user",req.validated.params.id);res.status(204).end();}));
router.post("/users/:id/reset-password",requirePermission("USER_MANAGE"),validate(z.object({params:z.object({id:UUID}),body:z.object({temporaryPassword:z.string().min(12)})})),asyncHandler(async(req,res)=>{const {temporaryPassword}=req.validated.body;const userId=req.validated.params.id;await resetPasswordWithTemporaryCredential(userId,temporaryPassword);await audit(req,"USER_PASSWORD_RESET","user",userId);res.status(204).end();}));
router.get("/roles",requirePermission("USER_MANAGE"),asyncHandler(async(req,res)=>res.json({items:await db.select().from(roles),permissions:await db.select().from(permissions)})));

const uploadSchema=z.object({employeeId:UUID,year:z.number().int().min(2000).max(2100),month:z.number().int().min(1).max(12),documentType:z.enum(["SALARY","SAC","VACATION","FINAL_SETTLEMENT","ADJUSTMENT","OTHER"]).default("SALARY"),title:z.string().max(200).optional(),originalFileName:z.string().regex(/\.pdf$/i),mimeType:z.literal("application/pdf"),sizeBytes:z.number().int().positive().max(10*1024*1024),sha256:z.string().regex(/^[a-f0-9]{64}$/i).optional()});
const bulkItemSchema=uploadSchema.extend({clientId:z.string().min(1).max(100)});
async function createUploadIntent(data, userId) {
  const [employee] = await db.select({ id: employees.id, active: employees.active }).from(employees).where(eq(employees.id, data.employeeId));
  if (!employee || !employee.active) throw new ApiError(422, "El empleado seleccionado no existe o está inactivo");
  const id=randomUUID(),versionId=randomUUID(),storagePath=buildPayslipPath({employeeId:data.employeeId,year:data.year,month:data.month,payslipId:versionId});
  await db.insert(payslips).values({id,employeeId:data.employeeId,year:data.year,month:data.month,documentType:data.documentType,title:data.title,createdBy:userId});
  await db.insert(payslipVersions).values({id:versionId,payslipId:id,versionNumber:1,storagePath,originalFileName:data.originalFileName,mimeType:data.mimeType,sizeBytes:data.sizeBytes,sha256:data.sha256,uploadedBy:userId});
  try {
    return {payslipId:id,versionId,storagePath,upload:await createPayslipUploadUrl(storagePath)};
  } catch (error) {
    await db.update(payslipVersions).set({status:"FAILED"}).where(eq(payslipVersions.id,versionId));
    throw error;
  }
}
router.get("/me/payslips",requirePermission("PAYSLIP_VIEW_OWN"),asyncHandler(async(req,res)=>{if(!req.user.employeeId)return res.json({items:[]});const rows=await db.select({id:payslips.id,year:payslips.year,month:payslips.month,documentType:payslips.documentType,title:payslips.title,status:payslips.status,createdAt:payslips.createdAt}).from(payslips).where(and(eq(payslips.employeeId,req.user.employeeId),eq(payslips.status,"ACTIVE"))).orderBy(desc(payslips.year),desc(payslips.month));res.json({items:rows.map(r=>({...r,periodLabel:`${monthNames[r.month-1]} ${r.year}`,canDownload:true}))});}));
router.get("/admin/payslips",requirePermission("PAYSLIP_MANAGE"),asyncHandler(async(req,res)=>{const items=await db.select({id:payslips.id,year:payslips.year,month:payslips.month,status:payslips.status,documentType:payslips.documentType,employeeId:employees.id,employeeNumber:employees.employeeNumber,firstName:employees.firstName,lastName:employees.lastName}).from(payslips).innerJoin(employees,eq(payslips.employeeId,employees.id)).orderBy(desc(payslips.createdAt));res.json({items});}));
router.post("/admin/payslips/bulk-review",requirePermission("PAYSLIP_MANAGE"),validate(z.object({body:z.object({files:z.array(z.object({name:z.string().max(255),mimeType:z.string(),sizeBytes:z.number().int().positive().max(10*1024*1024)})).min(1).max(100)})})),asyncHandler(async(req,res)=>{const allEmployees=await db.select().from(employees).where(eq(employees.active,true));const items=req.validated.body.files.map(file=>{const match=/^(\d+)[_-](20\d{2})[_-](0[1-9]|1[0-2])(?:[_-].*)?\.pdf$/i.exec(file.name);const employee=match&&allEmployees.find(e=>e.employeeNumber===match[1]);const valid=file.mimeType==="application/pdf"&&/\.pdf$/i.test(file.name);return {fileName:file.name,sizeBytes:file.sizeBytes,valid,employeeId:employee?.id||null,employeeNumber:match?.[1]||null,year:match?Number(match[2]):null,month:match?Number(match[3]):null,status:!valid?"INVALID_FILE":employee?"READY":"UNMATCHED"};});res.json({items,summary:{ready:items.filter(i=>i.status==="READY").length,unmatched:items.filter(i=>i.status==="UNMATCHED").length,invalid:items.filter(i=>i.status==="INVALID_FILE").length}});}));
router.post("/admin/payslips/bulk-upload-intents",requirePermission("PAYSLIP_MANAGE"),validate(z.object({body:z.object({items:z.array(bulkItemSchema).min(1).max(100)})})),asyncHandler(async(req,res)=>{
  const results=[];
  for (const item of req.validated.body.items) {
    try { results.push({clientId:item.clientId,status:"READY",...(await createUploadIntent(item,req.user.id))}); }
    catch (error) { results.push({clientId:item.clientId,status:"FAILED",error:error instanceof ApiError ? error.message : "No se pudo preparar la carga"}); }
  }
  res.status(201).json({items:results,summary:{ready:results.filter(item=>item.status==="READY").length,failed:results.filter(item=>item.status==="FAILED").length}});
}));
router.post("/payslips/upload-intents",requirePermission("PAYSLIP_MANAGE"),validate(z.object({body:uploadSchema})),asyncHandler(async(req,res)=>res.status(201).json(await createUploadIntent(req.validated.body,req.user.id))));
async function assertPayslipAccess(req,id){const [item]=await db.select().from(payslips).where(eq(payslips.id,id));if(!item)throw new ApiError(404,"Recibo no encontrado");if(!req.user.permissions.includes("PAYSLIP_MANAGE")&&item.employeeId!==req.user.employeeId)throw new ApiError(403,"No puede acceder a este recibo");return item;}
router.post("/payslips/:id/confirm",requirePermission("PAYSLIP_MANAGE"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{const item=await assertPayslipAccess(req,req.validated.params.id);const [version]=await db.select().from(payslipVersions).where(and(eq(payslipVersions.payslipId,item.id),eq(payslipVersions.status,"PENDING")));if(!version)throw new ApiError(409,"No hay una carga pendiente");const object=await verifyPayslipObject(version.storagePath);if(!object)throw new ApiError(422,"El PDF no se encuentra en almacenamiento");if(object.sizeBytes&&object.sizeBytes!==version.sizeBytes)throw new ApiError(422,"El tamaño del archivo no coincide");await db.update(payslipVersions).set({status:"ACTIVE"}).where(eq(payslipVersions.id,version.id));await db.update(payslips).set({status:"ACTIVE",updatedAt:new Date()}).where(eq(payslips.id,item.id));await audit(req,"PAYSLIP_ACTIVATED","payslip",item.id);res.status(204).end();}));
router.post("/payslips/:id/replacement-intent",requirePermission("PAYSLIP_MANAGE"),validate(z.object({params:z.object({id:UUID}),body:uploadSchema.pick({originalFileName:true,mimeType:true,sizeBytes:true,sha256:true})})),asyncHandler(async(req,res)=>{const item=await assertPayslipAccess(req,req.validated.params.id);if(item.status!=="ACTIVE")throw new ApiError(409,"El recibo no está activo");const versions=await db.select().from(payslipVersions).where(eq(payslipVersions.payslipId,item.id));const versionId=randomUUID(),d=req.validated.body,storagePath=buildPayslipPath({employeeId:item.employeeId,year:item.year,month:item.month,payslipId:versionId});await db.insert(payslipVersions).values({id:versionId,payslipId:item.id,versionNumber:Math.max(...versions.map(v=>v.versionNumber))+1,storagePath,originalFileName:d.originalFileName,mimeType:d.mimeType,sizeBytes:d.sizeBytes,sha256:d.sha256,uploadedBy:req.user.id});res.status(201).json({payslipId:item.id,versionId,storagePath,upload:await createPayslipUploadUrl(storagePath)});}));
router.post("/payslips/:id/replacement-confirm",requirePermission("PAYSLIP_MANAGE"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{const item=await assertPayslipAccess(req,req.validated.params.id);const [pending]=await db.select().from(payslipVersions).where(and(eq(payslipVersions.payslipId,item.id),eq(payslipVersions.status,"PENDING"))).orderBy(desc(payslipVersions.versionNumber));if(!pending)throw new ApiError(409,"No hay reemplazo pendiente");if(!await verifyPayslipObject(pending.storagePath))throw new ApiError(422,"El PDF no se encuentra en almacenamiento");await db.update(payslipVersions).set({status:"REPLACED",replacedAt:new Date()}).where(and(eq(payslipVersions.payslipId,item.id),eq(payslipVersions.status,"ACTIVE")));await db.update(payslipVersions).set({status:"ACTIVE"}).where(eq(payslipVersions.id,pending.id));await audit(req,"PAYSLIP_REPLACED","payslip",item.id);res.status(204).end();}));
router.get("/payslips/:id/:action",(req,res,next)=>req.user?.permissions.includes("PAYSLIP_VIEW_OWN")||req.user?.permissions.includes("PAYSLIP_MANAGE")?next():next(new ApiError(403,"No tiene permisos para esta acción")),validate(z.object({params:z.object({id:UUID,action:z.enum(["view","download"])})})),asyncHandler(async(req,res)=>{const item=await assertPayslipAccess(req,req.validated.params.id);const [version]=await db.select().from(payslipVersions).where(and(eq(payslipVersions.payslipId,item.id),eq(payslipVersions.status,"ACTIVE")));if(!version)throw new ApiError(404,"Archivo no disponible");const url=req.validated.params.action==="view"?await createPayslipViewUrl(version.storagePath):await createPayslipDownloadUrl(version.storagePath);await audit(req,req.validated.params.action==="view"?"PAYSLIP_VIEWED":"PAYSLIP_DOWNLOADED","payslip",item.id);res.json({url});}));
router.post("/payslips/:id/archive",requirePermission("PAYSLIP_MANAGE"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{await assertPayslipAccess(req,req.validated.params.id);await db.update(payslips).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(payslips.id,req.validated.params.id));await audit(req,"PAYSLIP_ARCHIVED","payslip",req.validated.params.id);res.status(204).end();}));

async function assertAnnouncementVisible(req, id) {
  const [item] = await db.select().from(announcements).where(eq(announcements.id, id));
  if (!item) throw new ApiError(404, "Aviso no encontrado");
  if (req.user.permissions.includes("ANNOUNCEMENT_MANAGE")) return item;
  if (item.status !== "PUBLISHED" || (item.expiresAt && item.expiresAt <= new Date())) throw new ApiError(404, "Aviso no disponible");
  if (item.audienceType === "ALL") return item;
  if (!req.user.employeeId) throw new ApiError(403, "No puede acceder a este aviso");
  const memberships = await db.select({ areaId: employeeAreas.areaId }).from(employeeAreas).where(eq(employeeAreas.employeeId, req.user.employeeId));
  const links = await db.select({ areaId: announcementAreas.areaId }).from(announcementAreas).where(eq(announcementAreas.announcementId, id));
  if (!links.some(link => memberships.some(membership => membership.areaId === link.areaId))) throw new ApiError(403, "No puede acceder a este aviso");
  return item;
}
router.get("/announcements",requirePermission("ANNOUNCEMENT_VIEW"),asyncHandler(async(req,res)=>{const membership= req.user.employeeId ? await db.select({areaId:employeeAreas.areaId}).from(employeeAreas).where(eq(employeeAreas.employeeId,req.user.employeeId)) : [];const ids=membership.map(x=>x.areaId);const visible=await db.select().from(announcements).where(and(eq(announcements.status,"PUBLISHED"),or(isNull(announcements.expiresAt),gt(announcements.expiresAt,sql`unixepoch()`)))).orderBy(desc(announcements.publishedAt));const links=await db.select().from(announcementAreas);const reads=await db.select().from(announcementReads).where(eq(announcementReads.userId,req.user.id));res.json({items:visible.filter(a=>a.audienceType==="ALL"||links.some(l=>l.announcementId===a.id&&ids.includes(l.areaId))).map(a=>({...a,read:reads.some(r=>r.announcementId===a.id)}))});}));
router.get("/announcements/unread-count",requirePermission("ANNOUNCEMENT_VIEW"),asyncHandler(async(req,res)=>{const membership=req.user.employeeId?await db.select({areaId:employeeAreas.areaId}).from(employeeAreas).where(eq(employeeAreas.employeeId,req.user.employeeId)):[];const areaIds=membership.map(x=>x.areaId);const published=await db.select().from(announcements).where(and(eq(announcements.status,"PUBLISHED"),or(isNull(announcements.expiresAt),gt(announcements.expiresAt,sql`unixepoch()`))));const links=await db.select().from(announcementAreas);const reads=await db.select().from(announcementReads).where(eq(announcementReads.userId,req.user.id));const visible=published.filter(a=>a.audienceType==="ALL"||links.some(l=>l.announcementId===a.id&&areaIds.includes(l.areaId)));res.json({count:visible.filter(a=>!reads.some(r=>r.announcementId===a.id)).length});}));
router.post("/announcements",requirePermission("ANNOUNCEMENT_MANAGE"),validate(z.object({body:z.object({title:z.string().min(1).max(200),body:z.string().min(1).max(5000),priority:z.enum(["NORMAL","IMPORTANT","URGENT"]).default("NORMAL"),audienceType:z.enum(["ALL","AREAS"]).default("ALL"),areaIds:z.array(UUID).default([]),expiresAt:createAnnouncementExpiry,publishNow:z.boolean().default(false)})})),asyncHandler(async(req,res)=>{const d=req.validated.body;if(d.audienceType==="AREAS"&&!d.areaIds.length)throw new ApiError(422,"Seleccione al menos un área");const id=randomUUID();await db.insert(announcements).values({id,...d,status:d.publishNow?"PUBLISHED":"DRAFT",publishedAt:d.publishNow?new Date():null,publishedBy:d.publishNow?req.user.id:null});if(d.areaIds.length)await db.insert(announcementAreas).values(d.areaIds.map(areaId=>({announcementId:id,areaId})));await audit(req,"ANNOUNCEMENT_CREATED","announcement",id);res.status(201).json({id});}));
router.get("/admin/announcements",requirePermission("ANNOUNCEMENT_MANAGE"),asyncHandler(async(req,res)=>{const items=await db.select().from(announcements).orderBy(desc(announcements.createdAt));const links=await db.select().from(announcementAreas);res.json({items:items.map(item=>({...item,areaIds:links.filter(l=>l.announcementId===item.id).map(l=>l.areaId)}))});}));
router.get("/announcements/:id",requirePermission("ANNOUNCEMENT_VIEW"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>res.json({item:await assertAnnouncementVisible(req,req.validated.params.id)})));
router.patch("/announcements/:id",requirePermission("ANNOUNCEMENT_MANAGE"),validate(z.object({params:z.object({id:UUID}),body:z.object({title:z.string().min(1).max(200).optional(),body:z.string().min(1).max(5000).optional(),priority:z.enum(["NORMAL","IMPORTANT","URGENT"]).optional(),audienceType:z.enum(["ALL","AREAS"]).optional(),areaIds:z.array(UUID).optional(),expiresAt:updateAnnouncementExpiry})})),asyncHandler(async(req,res)=>{const {areaIds,...data}=req.validated.body;if(data.audienceType==="AREAS"&&areaIds?.length===0)throw new ApiError(422,"Seleccione al menos un área");await db.update(announcements).set({...data,updatedAt:new Date()}).where(eq(announcements.id,req.validated.params.id));if(areaIds){await db.delete(announcementAreas).where(eq(announcementAreas.announcementId,req.validated.params.id));if(areaIds.length)await db.insert(announcementAreas).values(areaIds.map(areaId=>({announcementId:req.validated.params.id,areaId})));}await audit(req,"ANNOUNCEMENT_UPDATED","announcement",req.validated.params.id);res.status(204).end();}));
router.post("/announcements/:id/read",requirePermission("ANNOUNCEMENT_VIEW"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{await assertAnnouncementVisible(req,req.validated.params.id);await db.insert(announcementReads).values({announcementId:req.validated.params.id,userId:req.user.id}).onConflictDoNothing();await audit(req,"ANNOUNCEMENT_READ","announcement",req.validated.params.id);res.status(204).end();}));
router.post("/announcements/:id/publish",requirePermission("ANNOUNCEMENT_PUBLISH"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{await db.update(announcements).set({status:"PUBLISHED",publishedAt:new Date(),publishedBy:req.user.id,updatedAt:new Date()}).where(eq(announcements.id,req.validated.params.id));await audit(req,"ANNOUNCEMENT_PUBLISHED","announcement",req.validated.params.id);res.status(204).end();}));
router.post("/announcements/:id/archive",requirePermission("ANNOUNCEMENT_MANAGE"),validate(z.object({params:z.object({id:UUID})})),asyncHandler(async(req,res)=>{await db.update(announcements).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(announcements.id,req.validated.params.id));await audit(req,"ANNOUNCEMENT_ARCHIVED","announcement",req.validated.params.id);res.status(204).end();}));
export default router;
